{"name": "test_Visit", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'telligent-co...orization-web' == '簡訊登入'\n  - 簡訊登入\n  + telligent-consumer-authorization-web", "trace": "@allure.story('進入SSO頁面')\n    def test_Visit():\n    \n            driver.get(\"https://qa.telli.cc/consumer/oauth2/login?ReturnUrl=%2Fconsumer%2Foauth2%2Fconnect%2Fauthorize%3Fclient_id%3Dauthorization-code-client%26redirect_uri%3Dhttps%253A%252F%252Fqa.telli.cc%252Fconsumer%252Fmember%252Fcallback%26response_type%3Dcode%26scope%3D%2520%26state%3D3e390076cc644b3788ed41ed39f2d69d%26code_challenge%3DIlR89jtBkm3IK3MQ4GEat-rfLQAIfsyZ8pRaw_nYbkg%26code_challenge_method%3DS256%26response_mode%3Dquery%26companyId%3D97d288ac-5f17-11ed-afa6-00ffaf2156c9\")\n            time.sleep(3)\n            x = driver.title\n>           assert x ==\"簡訊登入\"\nE           AssertionError: assert 'telligent-co...orization-web' == '簡訊登入'\nE             - 簡訊登入\nE             + telligent-consumer-authorization-web\n\nSSSO_login_test.py:49: AssertionError"}, "start": 1669188654016, "stop": 1669188657037, "uuid": "2179aff2-d978-499a-a4d1-5b36b0d1e260", "historyId": "0e1460fca3f18f45856145e52815562c", "testCaseId": "221caac009e6a3117a13d142b0c212d2", "fullName": "SSSO_login_test#test_Visit", "labels": [{"name": "story", "value": "進入SSO頁面"}, {"name": "suite", "value": "SSSO_login_test"}, {"name": "host", "value": "C010700042"}, {"name": "thread", "value": "7788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "SSSO_login_test"}]}